


redis:
  # !!! Не трогайте если не знаете что делать

  # Если хотите Синхронизацию данных между серверами
  # то Redis хорошо подходит для этого.

  enable: false
  host: localhost
  port: 6379
  password: ""

placeholders:
  notFound: "&cне найден"
  player: "&d%player% (x %progress%)"

  formattedTime:
    seconds:
      form1: 'секунду'
      form2: 'секунды'
      form3: 'секунд'
    minutes:
      form1: 'минуту'
      form2: 'минуты'
      form3: 'минут'
    hours:
      form1: 'час'
      form2: 'часа'
      form3: 'часов'


AutoStart:
  MinPlayers: 3
  TimeZone: UTC+3
  times:
    - '10:00'
    - '13:00'
    - '16:00'
    - '19:00'
    - '22:00'



hologram-location: {}

holo:
  - "&7« &dЗахват ресурсов &7»"
  - ""
  - "Захватчик &7- &fвиртуальный персонаж"
  - "который включает &dмножество событий."
  - ""
  - "Каждое событие - это &dсоревновательное &fзадания,"
  - "каждое из которых имеет &dвременные &fограничения."
  - ""
  - "Лучший игрок, который займёт &dтоп 1"
  - "получит &dценные &fнаграды!"
  - ""
  - "Расписание ивента &7(по МСК)"
  - "&d10:00, 13:00, 16:00, 19:00, 22:00"
  - ""
  - "&cЗахватчик пока что не приходил"
